version: '3'

services:
  translation-api:
    image: ghcr.io/tartunlp/translation-worker:latest
    ports:
      - "8000:8000"
    restart: unless-stopped

  tts-api:
    image: ghcr.io/tartunlp/text-to-speech-api:latest
    ports:
      - "8001:8000"
    restart: unless-stopped
